### ISSUE TITLE
BetaSplit Checklist

### ISSUE THREAD

**Issue by TrevorJTClarke** [CronCats/cw-croncat#264]
- [ ]  Remove random/template files like markdown that are unused
- [ ]  Remove Comments/unused code
- [ ]  Resolve any pending TODOs (or remove if unneeded)
